### ISSUE TITLE
Add ability to execute pipelines with single-end sequencing data

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#64] opened 2018-11-16 20:01 UTC
Imported from GitLab issue #390.  Originally posted on 2016/08/02 11:27AM

**Comment by apetkau** [comment] 2018-11-16 20:01
This feature was requested again in https://github.com/phac-nml/irida/issues/53

Imported from GitLab.  Originally posted on 2018/09/28 11:23AM

**Comment by tom114** [comment] 2019-05-10 16:43
Closing as duplicate of #53

**Closed by tom114** 2019-05-10 16:43 UTC
Labels: tools
