### ISSUE TITLE
Deleting "saved pipeline parameters" 

### ISSUE THREAD

**Issue by ajkarloss** [phac-nml/irida#1251] opened 2022-04-25 06:51 UTC
We have added/tested  the pipelines with different sets of parameters and saved them by different names. We want the users to use only one set of parameters and delete other unused parameters which are saved in different names.
F. Ex. For Assembly and Annotation pipeline We have "default", "Params-1", "Params-2", "Params-3"...."Params-10" in the drop down menu. We want to delete all saved parameter sets except the "Params-2" and keep that as default. Thanks.

**Comment by ericenns** [comment] 2022-07-20 14:45
Duplicate of #69

**Closed by ericenns** 2022-07-20 14:45 UTC
Labels: enhancement
