### ISSUE TITLE
Strange character at end of "Searching"

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#23] opened 2018-03-31 20:47 UTC
Seeing a minor bug when adding a new sample at /project/<id>/sample/new.

A strange character appears at the end of "Searching" that pops up while I'm typing in the organism name.  

I can see it in Safari and Chrome on macOS High Sierra 10.13.3.

**Comment by apetkau** [comment] 2018-03-31 21:08
Thanks @glwinsor, I think I may know what character you're referring to as I've sometimes seen it.  @joshsadam may have more information.

**Comment by dfornika** [comment] 2018-03-31 22:31
![searching-character](https://user-images.githubusercontent.com/145659/38168117-920e10a6-34f8-11e8-9ade-f152c0a64ed0.png)

**Comment by joshsadam** [comment] 2018-04-03 16:28
This is part of an issue that I actually am currently working on.  You will notice that there is a larger issue with this select2 dropdown --> you cannot select broader level taxonomic terms.

e.g. If you search `esc` you will get back:

![select2](https://user-images.githubusercontent.com/11295750/38261510-0d9944f0-3730-11e8-917c-1ec9b4b49fcf.png)

The problem is, and completely my fault for not catching this, when I updated to the latest release of [Select2](https://select2.org/) (v.4.0.3) it only uses a proper `select` tag.  These broader taxonomic terms are created as `optgroup`s which cannot be selected (by nature of html).

Currently I am reverting back to an older version of Select2 (v.3.5.0). Moving forward, we may need to consider a better selection mechanism for these datasets that are backed by complex ontologies.

One way I am considering going is moving towards using [React](https://reactjs.org/) and utilizing the [Ant Design Framework](https://ant.design/).  They have lots of well tested and used components (>26k stars on [GitHub](https://github.com/ant-design/ant-design)), but particularly interesting and applicable to this issue is the [TreeSelect](https://ant.design/components/tree-select/).

This is obviously an overarching architecture issue for IRIDA that is beyond the scope of this issue, but I would appreciate any and all feedback on it.  @peterk87 and I have spoken quite a bit about slowly removing all the angularjs scripts from the project migrating towards something like React or Vuejs.

**Comment by joshsadam** [comment] 2018-04-05 16:14
This has been updated for the "Add Sample to Project" page in our in-house gitlab (merge request !1293).  If you find more of these please let me know and I will fix them.  Thanks 😀

**Closed by joshsadam** 2018-04-05 16:14 UTC
Labels: UI, bug
