### ISSUE TITLE
ReferenceError: page is not defined

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#27] opened 2018-04-05 16:58 UTC
We found a bug on the analysis /<analysis_id> details page when you click on the "Download Files" link under "Output Files". Nothing happens when you click on this link which is kind of odd because I thought it was working before (maybe it was the previous version though).

Here's the console output that I see when clicking on the link. It throws a ReferenceError:

![screen shot 2018-04-05 at 9 39 31 am](https://user-images.githubusercontent.com/824607/38379320-369745e2-38b5-11e8-95e9-90e89e605839.png)

I also notice the following error when the page initially loads but I don't know if it's related:

![screen shot 2018-04-05 at 9 56 06 am](https://user-images.githubusercontent.com/824607/38380118-aabdceee-38b7-11e8-90ae-d74b34b590a2.png)

On my end I'll check and see if the zip file is being created and get back to you on that.

EDIT: For clarity, we are using irida-0.20.0.

**Comment by apetkau** [comment] 2018-04-05 17:10
I do not get the same error myself, but I can confirm that I cannot download zip files of the analysis results, both in our current production system and in our latest development branch.

@joshsadam could you look into this?

**Comment by dfornika** [comment] 2018-04-05 17:14
This was reported in issue !616 on the GitLab issue tracker:

https://irida.corefacility.ca/irida/irida/issues/616

I believe that it's been fixed in the latest bugfix release (v0.20.1)

**Comment by apetkau** [comment] 2018-04-05 18:08
Thanks @dfornika.  Testing a bit more, it looks like downloading output files is all working for me too.  It must have been a random browser/cache issue I encountered before.

Sorry @joshsadam, false alarm.

**Closed by apetkau** 2018-04-05 18:08 UTC
